from .analysis import SUPPORTED_REPO_TYPES, analyze_repo
from .builders import (
    AGENT_LOCALE_OUTPUT_ROOTS,
    DEFAULT_HUMAN_TEMPLATE_BY_LOCALE,
    HUMAN_LOCALE_OUTPUT_ROOTS,
    HUMAN_PAIRED_PATH_RULES,
    SUPPORTED_DOC_PROFILES,
    SUPPORTED_AGENT_LOCALES,
    SUPPORTED_HUMAN_LOCALES,
    SUPPORTED_HUMAN_TEMPLATE_VARIANTS,
    SUPPORTED_OUTPUT_MODES,
    generate_docs,
    generate_human_docs,
    repo_type_label,
    resolve_agent_output_root,
    resolve_human_output_root,
    resolve_human_template_variant,
)
from .engine import (
    SUPPORTED_ENGINE_ACTIONS,
    EngineExecutionResult,
    EngineRequest,
    GenerationPlan,
    apply_generation_plan,
    build_analysis_explanation_lines,
    build_generation_plan,
    effective_profile_for_mode,
    execute_engine_request,
    plan_dry_run_actions,
    plan_title,
    suggest_profile,
    write_strategy_for_mode,
)
from .markdown import MANUAL_END, MANUAL_START, merge_markdown
from .utils import infer_project_name, read_text, write_file

__all__ = [
    "MANUAL_END",
    "MANUAL_START",
    "SUPPORTED_REPO_TYPES",
    "SUPPORTED_DOC_PROFILES",
    "SUPPORTED_HUMAN_TEMPLATE_VARIANTS",
    "SUPPORTED_HUMAN_LOCALES",
    "SUPPORTED_AGENT_LOCALES",
    "SUPPORTED_OUTPUT_MODES",
    "AGENT_LOCALE_OUTPUT_ROOTS",
    "HUMAN_LOCALE_OUTPUT_ROOTS",
    "DEFAULT_HUMAN_TEMPLATE_BY_LOCALE",
    "HUMAN_PAIRED_PATH_RULES",
    "SUPPORTED_ENGINE_ACTIONS",
    "EngineExecutionResult",
    "EngineRequest",
    "GenerationPlan",
    "analyze_repo",
    "apply_generation_plan",
    "build_analysis_explanation_lines",
    "build_generation_plan",
    "effective_profile_for_mode",
    "execute_engine_request",
    "generate_docs",
    "generate_human_docs",
    "infer_project_name",
    "merge_markdown",
    "plan_dry_run_actions",
    "plan_title",
    "suggest_profile",
    "write_strategy_for_mode",
    "repo_type_label",
    "resolve_agent_output_root",
    "resolve_human_output_root",
    "resolve_human_template_variant",
    "read_text",
    "write_file",
]
