from __future__ import annotations

import re


def translate_to_zh(text: str) -> str:
    # This layer localizes fixed rules, headings, and contract phrases so zh outputs
    # do not contain large English blocks. It does not claim polished human translation.
    mapping = [
        ("# AGENTS", "# 智能体核心架构总览"),
        ("# Product", "# 产品意图与业务核心"),
        ("# Architecture", "# 系统架构与边界"),
        ("# Execution", "# 运行与执行手册"),
        ("# Memory", "# 术语表与知识记忆"),
        ("# Project Overview", "# 项目总体概览"),
        ("# Workflows", "# 工作流"),
        ("# Glossary", "# 术语表"),
        ("## What This Project Is", "## 项目定位与愿景"),
        ("## Best Used For", "## 最佳适用场景"),
        ("## Dual Documentation System", "## 双重视图文档系统"),
        ("## Repository Classification", "## 仓库分类与判定"),
        ("## Files", "## 核心文件结构"),
        ("## Top Rules (Read First)", "## 核心规则（首读）"),
        ("## Confirmed Facts", "## 已确认事实"),
        ("## Constraints To Preserve", "## 必须保持的约束"),
        ("## Supporting Doc Synthesis", "## 支持文档综合"),
        ("## Referenced Repository Docs", "## 参考仓库文档"),
        ("## Open Questions", "## 待解决问题"),
        ("## Setup", "## 安装"),
        ("## Run", "## 运行"),
        ("## Verify", "## 验证"),
        ("## Synthesis Summary", "## 综合摘要"),
        ("## Knowledge Status", "## 知识状态"),
        ("## Operational Notes", "## 运行说明"),
        ("## Update Triggers", "## 更新触发条件"),
        ("## Maintenance Workflow", "## 维护流程"),
        ("## Bootstrap Backlog", "## 冷启动待办"),
        ("## Bootstrap Backlog (When Docs Are Thin)", "## 冷启动待办（文档较薄时）"),
        ("## Provenance", "## 溯源"),
        ("## Document Contract", "## 文档契约"),
        ("## Dual Sync Checklist", "## 双视图同步检查清单"),
        ("## Paired Refresh Rules", "## 成对刷新规则"),
        ("## Dual Pairing Contract (Rules)", "## 双视图配对契约（规则）"),
        ("## Paired Agent Docs (Dual Mode)", "## 配对的 Agent 文档（Dual 模式）"),
        ("## Output Boundary (Human vs Agent)", "## 输出边界（Human vs Agent）"),
        ("## Dual View Rationale", "## 双视图设计理由"),
        ("## Preserved Notes", "## 保留说明"),
        ("## Intended Audience", "## 目标读者"),
        ("## Key Entry Points", "## 关键入口"),
        ("## Current Priorities", "## 当前优先事项"),
        ("## Documentation Gaps To Close", "## 待补齐的文档空白"),
        ("## Confirmed Terms", "## 已确认术语"),
        ("## Naming Rules", "## 命名规则"),
        ("## Candidate Terms From Code Signals", "## 代码信号提取的候选术语"),
        ("## Derived Terminology Signals", "## 推导出的术语信号"),
        ("## Unresolved Terminology Items", "## 未决术语项"),
        ("## Conflicting Terminology Signals", "## 冲突术语信号"),
        ("## Users and Outcomes", "## 用户与结果"),
        ("## Entry Surfaces", "## 入口面"),
        ("## Surfaces", "## 入口面"),
        ("## Guidance", "## 指引"),
        ("## Source of Truth", "## 真相源"),
        ("## Detected Signals", "## 检测到的信号"),
        ("## System Map", "## 系统地图"),
        ("## Stability Boundaries", "## 稳定性边界"),
        ("### Confirmed Facts", "### 已确认事实"),
        ("### Confirmed Rules", "### 已确认规则"),
        ("### Supporting Signals", "### 辅助信号"),
        ("### Decision Backlog", "### 决策待办"),
        ("### Conflict Watchlist", "### 冲突观察清单"),
        ("### Confirmed", "### 已确认"),
        ("### Conflicting", "### 冲突"),
        ("### Unresolved", "### 未决"),
        ("Product positioning:", "产品定位："),
        ("Repository adaptation scope:", "仓库适配范围："),
        ("Retention value:", "留存价值："),
        ("Positioning guardrail:", "定位护栏："),
        ("this repository is scoped for CLI coding-agent workflows, not a standalone end-user application.", "本仓库面向 CLI coding-agent 工作流，而不是独立终端用户应用。"),
        ("this repository is scoped for CLI coding-agent workflows, not a standalone end-user application", "本仓库面向 CLI coding-agent 工作流，而不是独立终端用户应用"),
        ("fit repositories that need ongoing refresh/governance workflows, not one-off documentation scans.", "适用于需要持续 refresh/治理工作流的仓库，而不是一次性文档扫描。"),
        ("fit repositories that need ongoing refresh/governance workflows, not one-off documentation scans", "适用于需要持续 refresh/治理工作流的仓库，而不是一次性文档扫描"),
        ("prioritize repeatable `init -> refresh -> doctor` lifecycle checks so documentation stays governable, not a one-shot generator output.", "优先保证可重复的 `init -> refresh -> doctor` 生命周期检查，使文档保持可治理，而不是一次性生成产物。"),
        ("prioritize repeatable `init -> refresh -> doctor` lifecycle checks so documentation stays governable, not a one-shot generator output", "优先保证可重复的 `init -> refresh -> doctor` 生命周期检查，使文档保持可治理，而不是一次性生成产物"),
        ("describe `docagent` as an ongoing documentation system (`init/refresh/doctor/migrate`), not a one-shot markdown generator.", "将 `docagent` 描述为持续运行的文档系统（`init/refresh/doctor/migrate`），而不是一次性 Markdown 生成器。"),
        ("describe `docagent` as an ongoing documentation system (`init/refresh/doctor/migrate`), not a one-shot markdown generator", "将 `docagent` 描述为持续运行的文档系统（`init/refresh/doctor/migrate`），而不是一次性 Markdown 生成器"),
        ("Architecture rationale lives in", "架构说明位于"),
        ("while operational boundaries for agents live in paired AGENTS architecture docs", "而面向 agent 的运行边界位于配对的 AGENTS 架构文档中"),
        ("Architecture is split between a frontend surface and a backend/runtime surface.", "架构分为前端界面层和后端/运行时层。"),
        ("Source-of-truth boundary:", "真相源边界："),
        ("CLI boundary:", "CLI 边界："),
        ("Build-path rule:", "构建路径规则："),
        ("Distribution structure:", "分发结构："),
        ("Verification gate:", "验证关卡："),
        ("Verification order:", "验证顺序："),
        ("Execution contract:", "执行契约："),
        ("Failure triage priority:", "失败排查优先级："),
        ("Execution constraints:", "执行约束："),
        ("Product pairing rule:", "产品配对规则："),
        ("Architecture pairing rule:", "架构配对规则："),
        ("Execution pairing rule:", "执行配对规则："),
        ("Refresh contract:", "刷新契约："),
        ("Path contract:", "路径契约："),
        ("Quad-mode contract:", "Quad 模式契约："),
        ("Current repo shape:", "当前仓库形态："),
        ("Read product and architecture docs before broad refactors.", "在进行大范围重构前，先阅读产品和架构文档。"),
        ("Refresh `AGENTS/` after meaningful repo-shape, workflow, or terminology changes.", "当仓库结构、工作流或术语发生实质变化后，刷新 `AGENTS/`。"),
        ("Refresh `dfa-doc/AGENTS/` after meaningful repo-shape, workflow, or terminology changes.", "当仓库结构、工作流或术语发生实质变化后，刷新 `dfa-doc/AGENTS/`。"),
        ("Prefer confirmed facts over speculative roadmap language.", "优先采用已确认事实，而不是猜测性的路线图措辞。"),
        ("Protect hand-maintained notes with manual blocks when refresh safety matters.", "当刷新安全性重要时，用 manual blocks 保护手工维护的说明。"),
        ("Keep the skill manifest, SKILL.md instructions, and generator behavior aligned.", "保持 skill 清单、SKILL.md 指令和生成器行为一致。"),
        ("State repository scope and user value as explicit rules before writing broad product narrative.", "在撰写宽泛的产品叙述前，先将仓库范围和用户价值写成明确规则。"),
        ("Use lifecycle language (`init/refresh/doctor/migrate`) to keep docs maintainable over one-shot generation.", "使用生命周期语言（`init/refresh/doctor/migrate`）保持文档可持续维护，而不是一次性生成。"),
        ("keep `docagent` as the single entry surface for `codex`, `claude`, `continue`, `copilot` workflows.", "保持 `docagent` 作为 `codex`、`claudecode`、`continue`、`copilot` 工作流的统一入口。"),
        ("keep `docagent` as the single entry surface for `codex`, `claude`, `continue`, `copilot` workflows", "保持 `docagent` 作为 `codex`、`claudecode`、`continue`、`copilot` 工作流的统一入口"),
        ("on conflicts, arbitrate against `readme.md`, `docs/platforms.md`, `docs/platforms.zh.md` before changing CLI entry, adapter wiring, or distribution behavior.", "当出现冲突时，在修改 CLI 入口、adapter wiring 或分发行为前，先以 `readme.md`、`docs/platforms.md`、`docs/platforms.zh.md` 为裁决依据。"),
        ("on conflicts, arbitrate against `readme.md`, `docs/platforms.md`, `docs/platforms.zh.md` before changing CLI entry, adapter wiring, or distribution behavior", "当出现冲突时，在修改 CLI 入口、adapter wiring 或分发行为前，先以 `readme.md`、`docs/platforms.md`、`docs/platforms.zh.md` 为裁决依据"),
        ("keep platform mappings in adapter/config docs (`Claude Code` -> `docagent init --ai claudecode`) while CLI contract changes stay centralized.", "将平台映射保留在 adapter/config 文档中（`Claude Code` -> `docagent init --ai claudecode`），而 CLI 契约变更保持集中管理。"),
        ("Treat source-of-truth files as canonical when supporting docs disagree.", "当支持文档存在分歧时，以 source-of-truth 文件为准。"),
        ("Refresh both `dfa-doc/handbook/` and `dfa-doc/AGENTS/` after architecture-impacting changes.", "当架构相关变更发生后，同时刷新 `dfa-doc/handbook/` 和 `dfa-doc/AGENTS/`。"),
        ("Treat the first visible or invoked surface as part of the product contract.", "将第一个可见或被调用的入口视为产品契约的一部分。"),
        ("Keep user-facing names aligned across README examples, manifests, routes, and commands.", "在 README 示例、清单、路由和命令之间保持面向用户的名称一致。"),
        ("Treat install, invocation, and prompt surfaces as the equivalent of a frontend contract.", "将安装、调用和提示词入口视为等同于前端契约。"),
        ("Preserve route semantics and component hierarchy before redesigning layout or navigation.", "在重设计布局或导航之前，保持路由语义和组件层级。"),
        ("Resolve source-of-truth conflicts before editing CLI, adapter, or build-path behavior.", "在修改 CLI、adapter 或构建路径行为前，先解决 source-of-truth 冲突。"),
        ("When source-of-truth files move, update references in both doc systems before adjusting adapter/build-path rules.", "当 source-of-truth 文件移动时，先更新两套文档系统中的引用，再调整 adapter/构建路径规则。"),
        ("Aligning agents on who this repository serves", "让多个 agent 对仓库服务对象达成一致"),
        ("Checking whether a change still supports the intended user journey", "检查改动是否仍支持预期用户路径"),
        ("Confirm the primary audience and the exact outcome they expect from this repository.", "确认主要受众以及他们期望从该仓库获得的具体结果。"),
        ("Confirm which behaviors or labels must remain stable for downstream users.", "确认哪些行为或标签必须对下游用户保持稳定。"),
        ("This page is maintainer-facing source-of-truth for its domain; keep it synchronized with `dfa-doc/AGENTS/` in dual mode and `dfa-doc/handbook.zh/` as the human-view root.", "本页是该领域面向维护者的真相源；在 dual 模式下保持与 `dfa-doc/AGENTS/` 同步，并以 `dfa-doc/handbook.zh/` 作为人类视图根目录。"),
        ("This page is maintainer-facing source-of-truth for its domain; keep it synchronized with `dfa-doc/AGENTS/` in dual mode and `dfa-doc/handbook/` as the human-view root.", "本页是该领域面向维护者的真相源；在 dual 模式下保持与 `dfa-doc/AGENTS/` 同步，并以 `dfa-doc/handbook/` 作为人类视图根目录。"),
        ("Record scope decisions as explicit rules and owners; move stale discussion text to decision backlog.", "将范围决策记录为明确规则和负责人；把过时讨论移入决策待办。"),
        ("Update this page in the same PR as behavior changes; avoid narrative-only refreshes without command or contract changes.", "在行为变更的同一 PR 中更新本页；避免在没有命令或契约变化时做纯叙述式刷新。"),
        ("Keep terminology and decision memory aligned with current docs and command surfaces.", "保持术语与决策记忆和当前文档、命令入口一致。"),
        ("After edits, refresh in dual mode and verify both `dfa-doc/AGENTS/` and `dfa-doc/handbook.zh/` were updated in the same change set.", "编辑后用 dual 模式刷新，并确认 `dfa-doc/AGENTS/` 与 `dfa-doc/handbook.zh/` 在同一组变更中一起更新。"),
        ("After edits, refresh in dual mode and verify both `dfa-doc/AGENTS/` and `dfa-doc/handbook/` were updated in the same change set.", "编辑后用 dual 模式刷新，并确认 `dfa-doc/AGENTS/` 与 `dfa-doc/handbook/` 在同一组变更中一起更新。"),
        ("If one side changed without the other, treat it as documentation drift and resolve before merge.", "如果只更新了一侧，将其视为文档漂移，并在合并前解决。"),
        ("Run documented verify commands after refresh and keep failure-triage order aligned across both doc systems.", "刷新后运行文档中记录的 verify 命令，并保持两套文档系统中的故障排查顺序一致。"),
        ("When scope or audience changes, update project positioning and retention rules in both doc systems together.", "当范围或受众变化时，在两套文档系统中同时更新项目定位与留存规则。"),
        ("run one refresh/generate action that updates paired views together; do not patch one locale/audience in isolation.", "一次 refresh/generate 应同时更新成对视图；不要单独修补某个 locale 或 audience。"),
        ("Locale-output rule: human locale `zh` maps to `dfa-doc/handbook.zh/`.", "语言输出规则：人类视图语言 `zh` 映射至目录 `dfa-doc/handbook.zh/`。"),
        ("Locale-output rule: human locale `en` maps to `dfa-doc/handbook/`.", "语言输出规则：人类视图语言 `en` 映射至目录 `dfa-doc/handbook/`。"),
        ("Template rule: human template variant `paired-core` remains part of the pairing contract and must stay aligned across paired docs.", "模板规则：human 模板变体 `paired-core` 属于配对契约的一部分，必须在配对文档间保持一致。"),
        ("Path contract: verify changed files include both `dfa-doc/AGENTS*/` and `dfa-doc/handbook*/` counterparts when behavior changes affect shared source-of-truth.", "路径契约：当行为变更影响共享真相源时，验证变更文件同时包含 `dfa-doc/AGENTS*/` 与 `dfa-doc/handbook*/` 的对应项。"),
        ("Quad-mode contract: when using `--output-mode quad`, validate all four roots (`dfa-doc/AGENTS/`, `dfa-doc/AGENTS.zh/`, `dfa-doc/handbook/`, `dfa-doc/handbook.zh/`) in the same review cycle.", "Quad 模式契约：当使用 `--output-mode quad` 时，在同一轮审查中验证全部四个根目录（`dfa-doc/AGENTS/`、`dfa-doc/AGENTS.zh/`、`dfa-doc/handbook/`、`dfa-doc/handbook.zh/`）。"),
        ("Product pairing rule: if `dfa-doc/handbook.zh/overview.md` changes due to scope/value decisions, refresh paired product paths under both AGENTS roots.", "产品配对规则：如果 `dfa-doc/handbook.zh/overview.md` 因范围或价值决策变化而修改，同时刷新两个 AGENTS 根下对应的产品路径。"),
        ("Architecture pairing rule: if `dfa-doc/handbook.zh/architecture.md` changes due to boundary/source-of-truth updates, refresh paired architecture paths under both AGENTS roots.", "架构配对规则：如果 `dfa-doc/handbook.zh/architecture.md` 因边界或事实来源更新而修改，同时刷新两个 AGENTS 根下对应的架构路径。"),
        ("Execution pairing rule: if `dfa-doc/handbook.zh/workflows.md` changes due to command/order updates, refresh paired execution paths under both AGENTS roots.", "执行配对规则：如果 `dfa-doc/handbook.zh/workflows.md` 因命令或顺序更新而修改，同时刷新两个 AGENTS 根下对应的执行路径。"),
        ("Product pairing rule: if `dfa-doc/handbook/overview.md` changes due to scope/value decisions, refresh paired product paths under both AGENTS roots.", "产品配对规则：如果 `dfa-doc/handbook/overview.md` 因范围或价值决策变化而修改，同时刷新两个 AGENTS 根下对应的产品路径。"),
        ("Architecture pairing rule: if `dfa-doc/handbook/architecture.md` changes due to boundary/source-of-truth updates, refresh paired architecture paths under both AGENTS roots.", "架构配对规则：如果 `dfa-doc/handbook/architecture.md` 因边界或事实来源更新而修改，同时刷新两个 AGENTS 根下对应的架构路径。"),
        ("Execution pairing rule: if `dfa-doc/handbook/workflows.md` changes due to command/order updates, refresh paired execution paths under both AGENTS roots.", "执行配对规则：如果 `dfa-doc/handbook/workflows.md` 因命令或顺序更新而修改，同时刷新两个 AGENTS 根下对应的执行路径。"),
        ("Repository maintainers responsible for day-to-day delivery and operational stability.", "负责日常交付和运行稳定性的仓库维护者。"),
        ("Cross-functional engineers coordinating frontend and backend changes.", "协同前后端变更的跨职能工程师。"),
        ("Backend operators and API maintainers responsible for service behavior.", "负责服务行为的后端运维与 API 维护者。"),
        ("CLI maintainers preserving command UX and script compatibility.", "负责维护命令体验与脚本兼容性的 CLI 维护者。"),
        ("Skill maintainers keeping manifests, prompts, and generator behavior aligned.", "负责保持清单、提示词和生成器行为一致的 skill 维护者。"),
        ("Repository maintainers responsible for day-to-day delivery and operational stability", "负责日常交付和运行稳定性的仓库维护者"),
        ("Skill maintainers keeping manifests, prompts, and generator behavior aligned", "负责保持清单、提示词和生成器行为一致的 skill 维护者"),
        ("Project intent from README/code signals:", "从 README/代码信号推断的项目意图："),
        ("Repo type signal:", "仓库类型信号："),
        ("Both frontend and backend roots were detected.", "同时检测到了前端和后端根目录。"),
        ("Primary users are engineering teams who maintain automation workflows", "主要用户是维护自动化工作流的工程团队"),
        ("Dual-mode fixture for validating simultaneous human docs and AGENTS generation", "用于验证 human 文档与 AGENTS 同时生成的 dual-mode fixture"),
        ("Open question: decide whether on-prem deployment is required", "未决问题：确认是否需要本地部署（on-prem）"),
        ("Skill markers detected (`SKILL.md`, agent manifests, or an existing `AGENTS/` directory).", "检测到 skill 标记（`SKILL.md`、agent 清单或现有 `AGENTS/` 目录）。"),
        ("Conflict handling order: 1) check `readme.md`, `docs/platforms.md`, `docs/platforms.zh.md`; 2) then edit adapter/config mappings.", "冲突处理顺序：1）检查 `readme.md`、`docs/platforms.md`、`docs/platforms.zh.md`；2）再编辑 adapter/config 映射。"),
        ("Use `dfa-doc/handbook.zh/` for maintainer-facing policy and decisions; use `dfa-doc/AGENTS/` for execution order, command wiring, and handoff runbooks.", "使用 `dfa-doc/handbook.zh/` 记录面向维护者的政策与决策；使用 `dfa-doc/AGENTS/` 记录执行顺序、命令接线和交接运行手册。"),
        ("Use `dfa-doc/handbook/` for maintainer-facing policy and decisions; use `dfa-doc/AGENTS/` for execution order, command wiring, and handoff runbooks.", "使用 `dfa-doc/handbook/` 记录面向维护者的政策与决策；使用 `dfa-doc/AGENTS/` 记录执行顺序、命令接线和交接运行手册。"),
        ("Keep maintainer runbook context in `dfa-doc/handbook.zh/workflows.md`; keep step-by-step agent execution plan in `dfa-doc/AGENTS/workflows.md` (or layered execution docs).", "将维护者运行手册上下文保留在 `dfa-doc/handbook.zh/workflows.md` 中；将面向 agent 的步骤化执行计划保留在 `dfa-doc/AGENTS/workflows.md`（或分层执行文档）中。"),
        ("Keep maintainer runbook context in `dfa-doc/handbook.zh/workflows.md`; keep step-by-step agent execution plan in `dfa-doc/AGENTS/workflows.md` (or layered execution docs)", "将维护者运行手册上下文保留在 `dfa-doc/handbook.zh/workflows.md` 中；将面向 agent 的步骤化执行计划保留在 `dfa-doc/AGENTS/workflows.md`（或分层执行文档）中"),
        ("Maintainer runbook context lives in `dfa-doc/handbook.zh/workflows.md`, while step ordering for agent actions lives in paired `dfa-doc/AGENTS/` execution docs.", "维护者运行手册上下文位于 `dfa-doc/handbook.zh/workflows.md` 中，而智能体动作的步骤顺序位于配对的 `dfa-doc/AGENTS/` 执行文档中。"),
        ("Maintainer runbook context lives in `dfa-doc/handbook/workflows.md`, while step ordering for agent actions lives in paired `dfa-doc/AGENTS/` execution docs.", "维护者运行手册上下文位于 `dfa-doc/handbook/workflows.md` 中，而智能体动作的步骤顺序位于配对的 `dfa-doc/AGENTS/` 执行文档中。"),
        ("When the two views diverge, treat it as refresh drift rather than independent documentation authority.", "当两套视图出现分歧时，将其视为 refresh 漂移，而不是独立的文档权威。"),
        ("`dfa-doc/handbook.zh/` and `dfa-doc/AGENTS/` are two views generated from the same repository analysis and source-of-truth anchors.", "`dfa-doc/handbook.zh/` 与 `dfa-doc/AGENTS/` 是基于同一份仓库分析和事实锚点生成的两套视图。"),
        ("`dfa-doc/handbook/` and `dfa-doc/AGENTS/` are two views generated from the same repository analysis and source-of-truth anchors.", "`dfa-doc/handbook/` 与 `dfa-doc/AGENTS/` 是基于同一份仓库分析和事实锚点生成的两套视图。"),
        ("Run the main local command from README examples.", "运行 README 示例中的主本地命令。"),
        ("Run the main local command from README examples", "运行 README 示例中的主本地命令"),
        ("Primary command workflow centers on `npm` package scripts and repository-local verify commands.", "主要命令工作流围绕 `npm` package scripts 与仓库本地 verify 命令展开。"),
        ("Keep command examples in this file aligned with CI and README instructions.", "保持本文件中的命令示例与 CI 和 README 指令一致。"),
        ("Keep setup/run/verify/triage order executable from a clean checkout before marking this page done.", "在将本页标记为完成前，确保 setup/run/verify/triage 顺序可在干净 checkout 中执行。"),
        ("If a change affects both reader types, update both systems in one dual refresh cycle instead of patching only one side.", "如果一项变更影响两类读者，请在一次 dual refresh 周期中同时更新两套系统，而不是只修补一侧。"),
        ("No unresolved execution items were synthesized from supporting docs.", "未从支持文档中综合出未决的执行事项。"),
        ("No direct execution conflicts were synthesized from supporting docs.", "未从支持文档中综合出直接的执行冲突。"),
        ("is the documented command order for setup, sync, and drift checks.", "是安装、同步与漂移检查的文档化命令顺序。"),
        ("is the documented command order for setup, sync, and drift checks", "是安装、同步与漂移检查的文档化命令顺序"),
        ("workflow changes are not complete until `docagent doctor --target <repo-root>` pass.", "在 `docagent doctor --target <repo-root>` 通过前，workflow 变更不算完成。"),
        ("workflow changes are not complete until `docagent doctor --target <repo-root>` pass", "在 `docagent doctor --target <repo-root>` 通过前，workflow 变更不算完成"),
        ("keep `--target <repo-root>` explicit when commands run outside the target repo; keep `--output-mode agent` consistent across refresh runs; declare `--ai <platform>` explicitly so platform routing stays deterministic.", "当命令在目标仓库外运行时，显式保留 `--target <repo-root>`；在多次 refresh 之间保持 `--output-mode agent` 一致；显式声明 `--ai <platform>` 以保持平台路由确定。"),
        ("1) `docagent doctor --target <repo-root>`; stop at the first failing command before running later checks.", "1）先执行 `docagent doctor --target <repo-root>`；在运行后续检查前停在第一个失败命令。"),
        ("1) run `docagent doctor` first to catch install/config drift; 2) reconcile command context with `README.md`; 3) cross-check setup assumptions in `docs/quickstart.md`; 4) inspect CI logs for command/environment mismatches; 5) if failures persist, roll back generated docs to last known-good state and rerun `docagent refresh`.", "1）先运行 `docagent doctor` 捕获安装/配置漂移；2）结合 `README.md` 校对命令上下文；3）交叉检查 `docs/quickstart.md` 中的 setup 假设；4）检查 CI 日志中的命令/环境不匹配；5）若失败持续，回滚生成文档到最近一次可用状态并重新执行 `docagent refresh`。"),
        ("No supporting docs matched this role; content below is derived from repository structure and code signals.", "未找到该角色的支持文档；下方内容来自仓库结构和代码信号。"),
        ("Supporting docs were found; continue consolidating them into this page and archive stale duplicates.", "已找到支持文档；继续将它们整合进本页，并归档过时重复项。"),
        ("Assign one maintainer owner for this document and update it in the same pull request as behavior changes.", "为此文档指定一名维护负责人，并在行为变更的同一 PR 中更新它。"),
        ("Review this document at least once per sprint or before each release cut.", "每个 Sprint 或每次发版前至少审阅一次此文档。"),
        ("Update after roadmap, target user, or feature scope decisions.", "在路线图、目标用户或功能范围决策变更后更新。"),
        ("Update after boundary, dependency, or interface contract changes.", "在边界、依赖或接口契约变更后更新。"),
        ("Update after setup/run/verify command changes or CI workflow updates.", "在 setup/run/verify 命令或 CI 工作流变更后更新。"),
        ("Update when terminology, handoff language, or project status vocabulary changes.", "在术语、交接语言或项目状态用语变化时更新。"),
        ("When new user-facing routes, commands, or APIs are added, update scope and audience notes.", "当新增面向用户的路由、命令或 API 时，更新范围与受众说明。"),
        ("When priorities change in release planning, update the project overview and open decision list.", "当发版计划中的优先级变化时，更新项目概览和未决决策列表。"),
        ("When source-of-truth files, service boundaries, or runtime dependencies change, update this page.", "当 source-of-truth 文件、服务边界或运行时依赖变化时，更新本页。"),
        ("When integration contracts change (routes/endpoints/storage), refresh architecture notes in the same PR.", "当集成契约（routes/endpoints/storage）变化时，在同一 PR 中刷新架构说明。"),
        ("When setup/run/verify commands change, update this runbook immediately.", "当 setup/run/verify 命令变化时，立即更新此运行手册。"),
        ("When CI checks or release gates change, sync the Verify and Operational Notes sections.", "当 CI 检查或发布门禁变化时，同步更新 Verify 和运行说明部分。"),
        ("When teams introduce new domain terms, add canonical definitions and preferred wording.", "当团队引入新领域术语时，补充规范定义和推荐用语。"),
        ("When old terms are deprecated, keep migration aliases until docs and code are fully aligned.", "当旧术语被弃用时，在文档和代码完全对齐前保留迁移别名。"),
        ("Prioritize resolving conflicting statements before treating this document as canonical.", "在将此文档视为规范前，优先解决冲突表述。"),
        ("Track unresolved items as named decisions with owner and due date.", "将未决事项记录为带负责人和截止日期的具名决策。"),
        ("No major synthesis conflicts were detected; focus on keeping this page current with implementation changes.", "未检测到重大综合冲突；重点是在实现变化后保持本页最新。"),
        ("No supporting docs were found for this role; prioritize adding one maintainer-verified baseline note.", "未找到该角色的支持文档；优先补上一条由维护者确认的基线说明。"),
        ("No additional term candidates were derived from routes/endpoints.", "未从 routes/endpoints 中提取出额外候选术语。"),
        ("Keep user-facing names, commands, and labels consistent across docs and scripts.", "在文档与脚本之间保持面向用户的名称、命令和标签一致。"),
        ("Prefer canonical project terms over ad-hoc synonyms.", "优先使用规范项目术语，而不是临时同义词。"),
        ("No canonical terms were detected automatically.", "未自动检测到规范术语。"),
        ("No synthesis summary available.", "没有可用的综合摘要。"),
        ("No additional derived terminology signals were detected from repository structure.", "未从仓库结构中检测到额外的推导术语信号。"),
        ("No unresolved terminology or memory items were synthesized from supporting docs.", "未从支持文档中综合出未决术语或 memory 项。"),
        ("No conflicting terminology signals were synthesized from supporting docs.", "未从支持文档中综合出冲突术语信号。"),
        ("No explicit update triggers were derived automatically.", "未自动推导出明确的更新触发条件。"),
        ("No maintenance workflow suggestions were derived automatically.", "未自动推导出维护流程建议。"),
        ("No bootstrap backlog suggestions were derived automatically.", "未自动推导出 bootstrap 待办建议。"),
        ("No supporting memory documents were discovered outside generated outputs.", "在生成产物之外未发现支持性的 memory 文档。"),
        ("No supporting execution documents were discovered outside generated outputs.", "在生成产物之外未发现支持性的 execution 文档。"),
        ("Avoid drifting away from the repository's real code, scripts, and naming conventions.", "避免偏离仓库的真实代码、脚本和命名约定。"),
        ("Prefer stable entrypoints and contracts over broad structural churn.", "优先保持稳定的入口点和契约，而不是进行大范围结构改动。"),
        ("Review mixed signals before collapsing the repository into a single simplistic mental model.", "在把仓库简化成单一心智模型之前，先审查相互混杂的信号。"),
        ("Keep user-facing routes, labels, prompts, or commands stable unless the repository intentionally renames them.", "除非仓库明确进行了重命名，否则保持面向用户的路由、标签、提示词和命令稳定。"),
        ("Review README examples and visible entry surfaces before changing interaction flows.", "在改动交互流程前，先检查 README 示例和可见入口面。"),
        ("Treat skill manifests, trigger phrasing, and invocation prompts as the user-facing interface.", "将 skill 清单、触发措辞和调用提示视为面向用户的界面。"),
        ("Do not let manifest language drift away from what the generator actually supports.", "不要让清单中的表述偏离生成器真实支持的能力。"),
        ("Identify the runtime or automation entrypoint before changing behavior.", "在修改行为前先识别运行时或自动化入口点。"),
        ("Treat outputs, contracts, and side effects as downstream-facing surfaces.", "将输出、契约和副作用视为面向下游的接口面。"),
        ("The generator script and helper scripts are the backend-like execution layer.", "生成脚本和辅助脚本构成了类似后端的执行层。"),
        ("Prefer changing source code and configuration first, then refresh `dfa-doc/AGENTS/` docs.", "优先先改源码和配置，再刷新 `dfa-doc/AGENTS/` 文档。"),
        ("Do not let generated docs drift away from the repository's actual entrypoints and workflows.", "不要让生成文档偏离仓库真实的入口点和工作流。"),
        ("Skill manifests, README examples, and generator output should describe the same capability surface.", "skill 清单、README 示例和生成器输出应描述同一能力边界。"),
        ("Skill markers dominate classification, but packaged tooling signals suggest this repository may also ship installable utilities.", "skill 标记主导了当前分类结果，但已打包工具链的信号表明该仓库也可能提供可安装工具。"),
        ("Detected repo type:", "检测到的仓库类型："),
        ("Doc profile in use:", "当前使用的文档剖面："),
        ("Classification confidence:", "分类置信度："),
        ("Confirm the next milestone and keep this file updated with human-approved progress.", "确认下一个里程碑，并用人工确认后的进展持续更新此文件。"),
        ("Promote repeated domain terms into canonical glossary entries.", "将重复出现的领域术语提升为规范术语表条目。"),
        ("Note deprecated or ambiguous terms and map them to preferred wording.", "记录已弃用或有歧义的术语，并映射到推荐措辞。"),
        ("Review docs for vocabulary drift each sprint.", "每个 Sprint 检查一次文档中的术语漂移。"),
        ("No direct product conflicts were synthesized", "未综合出直接的产品冲突"),
        ("No unresolved product items were synthesized", "未综合出未决的产品事项"),
        ("No direct architecture conflicts were synthesized", "未综合出直接的架构冲突"),
        ("No unresolved architecture items were synthesized", "未综合出未决的架构事项"),
        ("No direct execution conflicts were synthesized", "未综合出直接的执行冲突"),
        ("No unresolved execution items were synthesized", "未综合出未决的执行事项"),
        ("No major product documentation gaps were detected", "未检测到明显的产品文档空白"),
        ("No direct project conflicts were synthesized", "未综合出直接的项目冲突"),
        ("No unresolved project items were synthesized", "未综合出未决的项目事项"),
        ("Wait for manual confirmation", "等待人工确认"),
        ("English | [简体中文](README.zh.md)", "[English](README.md) | 简体中文"),
        ("and operational stability", "以及运行稳定性"),
        ("- Rule 1:", "- 第一原则："),
        ("- Rule 2:", "- 第二原则："),
        ("- Rule 3:", "- 第三原则："),
        ("- Rule 4:", "- 第四原则："),
        ("- Rule 5:", "- 第五原则："),
        ("- Rule 6:", "- 第六原则："),
        ("- Rule 7:", "- 第七原则："),
        ("- Rule 8:", "- 第八原则："),
        ("Rule 1:", "第一原则："),
        ("Rule 2:", "第二原则："),
        ("Rule 3:", "第三原则："),
        ("Rule 4:", "第四原则："),
        ("Rule 5:", "第五原则："),
        ("Rule 6:", "第六原则："),
        ("Rule 7:", "第七原则："),
        ("Rule 8:", "第八原则："),
    ]

    translated = text
    mapping.sort(key=lambda item: len(item[0]), reverse=True)
    for en, zh in mapping:
        translated = translated.replace(en, zh)

    translated = re.sub(r"Sources analyzed: `(\d+)`", r"已分析信源数量：`\1`", translated)
    translated = re.sub(
        r"Synthesized statements: `(\d+)` confirmed, `(\d+)` conflicting, `(\d+)` unresolved",
        r"成功提炼结论：`\1` 条确认，`\2` 条冲突，`\3` 条未决",
        translated,
    )
    translated = re.sub(r"human locale `zh` maps to `dfa-doc/handbook.zh/`", r"中文语言包 `zh` 映射到 `dfa-doc/handbook.zh/`", translated)
    translated = re.sub(r"human locale `en` maps to `dfa-doc/handbook/`", r"英文语言包 `en` 映射到 `dfa-doc/handbook/`", translated)
    translated = re.sub(r"Path pair rule: `(.*)` pairs with `(.*)` for (.*)", r"路径对齐规则：`\1` 与 `\2` 结对，用于 \3", translated)
    translated = translated.replace("for agent-facing product rules and scope guardrails", "智能体侧的产品规则与范围护栏")
    translated = translated.replace("agent-facing product rules and scope guardrails", "智能体侧的产品规则与范围护栏")
    translated = translated.replace("for agent-facing user and outcome contract", "智能体侧的用户与交付契约")
    translated = translated.replace("agent-facing user and outcome contract", "智能体侧的用户与交付契约")
    translated = translated.replace("for agent-facing flow and entry-surface notes", "智能体侧的流程与入口说明")
    translated = translated.replace("agent-facing flow and entry-surface notes", "智能体侧的流程与入口说明")
    translated = translated.replace("for setup, verify, and failure-triage order", "安装、验证与排障顺序")
    translated = translated.replace("setup, verify, and failure-triage order", "安装、验证与排障顺序")
    translated = translated.replace("for stack facts and platform anchors", "栈事实与平台锚点")
    translated = translated.replace("stack facts and platform anchors", "栈事实与平台锚点")
    translated = translated.replace("for source-of-truth and compatibility rules", "source-of-truth 与兼容性规则")
    translated = translated.replace("source-of-truth and compatibility rules", "source-of-truth 与兼容性规则")
    translated = re.sub(r"\(sources: `.*`\)", "", translated)
    translated = translated.replace("`skill/meta repository`", "`技能/元数据类仓库`")
    translated = translated.replace("`web-app`", "`Web 应用程序`")
    translated = translated.replace("`cli-tool`", "`CLI 工具类仓库`")
    translated = translated.replace("`library-sdk`", "`库/SDK 类仓库`")
    translated = translated.replace("`backend-service`", "`后端服务类仓库`")
    return translated
