from .bootstrap import (
    build_architecture,
    build_backend,
    build_frontend,
    build_glossary,
    build_product,
    build_readme,
    build_workflows,
    generate_bootstrap_docs,
)
from .detectors import (
    append_package_script_commands,
    detect_generator_script,
    detect_package_metadata_paths,
    detect_root_package_scripts,
    detect_unittest_commands,
    detect_verify_script_commands,
    detect_workspace_config_paths,
    infer_source_of_truth_lines,
    product_entry_point_lines,
    supporting_docs_for_role,
)
from .helpers import (
    AGENT_LOCALE_OUTPUT_ROOTS,
    DEFAULT_HUMAN_TEMPLATE_BY_LOCALE,
    HUMAN_LOCALE_OUTPUT_ROOTS,
    HUMAN_PAIRED_PATH_RULES,
    SUPPORTED_AGENT_LOCALES,
    SUPPORTED_DOC_PROFILES,
    SUPPORTED_HUMAN_LOCALES,
    SUPPORTED_HUMAN_TEMPLATE_VARIANTS,
    SUPPORTED_OUTPUT_MODES,
    current_operating_posture,
    enumerate_rules,
    extend_unique,
    format_bullets,
    format_path_bullets,
    paired_agent_doc_lines,
    repo_type_label,
    resolve_agent_output_root,
    resolve_human_output_root,
    resolve_human_template_variant,
    role_first_screen_rules,
    supporting_doc_insight_lines,
    supporting_doc_lines,
    supporting_doc_provenance_lines,
    synthesis_summary_lines,
)
from .human import (
    build_human_architecture,
    build_human_glossary,
    build_human_overview,
    build_human_workflows,
    generate_human_docs,
)
from .layered import (
    build_layered_app_flow,
    build_layered_architecture_compatibility,
    build_layered_backend_structure,
    build_layered_core_goals,
    build_layered_entry,
    build_layered_frontend_guidelines,
    build_layered_implementation_plan,
    build_layered_lessons,
    build_layered_prd,
    build_layered_progress,
    build_layered_tech_stack,
    generate_layered_docs,
)


def generate_docs(analysis, locale: str = "en"):
    if analysis.doc_profile == "layered":
        return generate_layered_docs(analysis, locale=locale)
    return generate_bootstrap_docs(analysis, locale=locale)

__all__ = [
    "AGENT_LOCALE_OUTPUT_ROOTS",
    "DEFAULT_HUMAN_TEMPLATE_BY_LOCALE",
    "HUMAN_LOCALE_OUTPUT_ROOTS",
    "HUMAN_PAIRED_PATH_RULES",
    "SUPPORTED_AGENT_LOCALES",
    "SUPPORTED_DOC_PROFILES",
    "SUPPORTED_HUMAN_LOCALES",
    "SUPPORTED_HUMAN_TEMPLATE_VARIANTS",
    "SUPPORTED_OUTPUT_MODES",
    "append_package_script_commands",
    "build_architecture",
    "build_backend",
    "build_frontend",
    "build_glossary",
    "build_human_architecture",
    "build_human_glossary",
    "build_human_overview",
    "build_human_workflows",
    "build_layered_app_flow",
    "build_layered_architecture_compatibility",
    "build_layered_backend_structure",
    "build_layered_core_goals",
    "build_layered_entry",
    "build_layered_frontend_guidelines",
    "build_layered_implementation_plan",
    "build_layered_lessons",
    "build_layered_prd",
    "build_layered_progress",
    "build_layered_tech_stack",
    "build_product",
    "build_readme",
    "build_workflows",
    "current_operating_posture",
    "detect_generator_script",
    "detect_package_metadata_paths",
    "detect_root_package_scripts",
    "detect_unittest_commands",
    "detect_verify_script_commands",
    "detect_workspace_config_paths",
    "enumerate_rules",
    "extend_unique",
    "format_bullets",
    "format_path_bullets",
    "generate_bootstrap_docs",
    "generate_docs",
    "generate_human_docs",
    "generate_layered_docs",
    "infer_source_of_truth_lines",
    "paired_agent_doc_lines",
    "product_entry_point_lines",
    "repo_type_label",
    "resolve_agent_output_root",
    "resolve_human_output_root",
    "resolve_human_template_variant",
    "role_first_screen_rules",
    "supporting_doc_insight_lines",
    "supporting_doc_lines",
    "supporting_doc_provenance_lines",
    "supporting_docs_for_role",
    "synthesis_summary_lines",
]
