import type { VisualEffectDefinition } from './contracts.ts'

export const visualEffectManifest = [
  {
    id: 'horizontal-bend',
    chapter: 'frame',
    trigger: 'visible archive theme + scroll progress',
    fallback: 'real DOM rail with GradualBlur edges',
    reducedMotion: 'disabled',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'project-laser',
    chapter: 'projects',
    trigger: 'real Work title is readable and its local progress advances',
    fallback: 'the complete real title remains visible above an omitted local seam',
    reducedMotion: 'disabled',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'frame-title-particles',
    chapter: 'frame',
    trigger: 'the noninteractive Frame intro title is readable and its local progress advances',
    fallback: 'the real title remains visible without duplicating or dissolving a photograph',
    reducedMotion: 'static',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'particle-portal',
    chapter: 'frame + projects',
    trigger: 'explicit Frame archive entry or project case-study activation',
    fallback: 'atomic chapter landing or semantic dialog open without a visible intermediate scroll path',
    reducedMotion: 'static',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'footer-liquid-cursor',
    chapter: 'contact',
    trigger: 'pointer moves inside the readable Contact background on a fine pointer',
    fallback: 'the complete Contact DOM remains visible without the local dye field',
    reducedMotion: 'disabled',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'about-decrypt-reveal',
    chapter: 'about',
    trigger: 'identity dossier visible on a fine pointer with native HTML-in-Canvas',
    fallback: 'the complete semantic identity dossier remains visible as real DOM',
    reducedMotion: 'disabled',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'project-glass',
    chapter: 'projects',
    trigger: 'project list visible after the Work laser handoff settles',
    fallback: 'the complete interactive project list remains visible as real DOM',
    reducedMotion: 'disabled',
    contextCost: 1,
    license: 'MIT + Commons Clause',
    sourceUrl: 'https://github.com/DavidHDev/canvas-ui',
  },
  {
    id: 'project-case-dialog',
    chapter: 'projects',
    trigger: 'View case study activation',
    fallback: 'semantic project content and outbound links remain in document flow',
    reducedMotion: 'static',
    contextCost: 0,
    license: 'MIT',
    sourceUrl: 'https://github.com/mui/base-ui',
    packageName: '@base-ui/react',
  },
  {
    id: 'project-evidence-lightbox',
    chapter: 'frame + projects',
    trigger: 'real image activation',
    fallback: 'same-origin image link opens normally',
    reducedMotion: 'static',
    contextCost: 0,
    license: 'MIT',
    sourceUrl: 'https://github.com/dimsemenov/PhotoSwipe',
    packageName: 'photoswipe',
  },
  {
    id: 'project-metric-number-flow',
    chapter: 'projects',
    trigger: 'evidenced metric enters the viewport',
    fallback: 'accessible static final value',
    reducedMotion: 'static',
    contextCost: 0,
    license: 'MIT',
    sourceUrl: 'https://github.com/barvian/number-flow',
    packageName: '@number-flow/react',
  },
  {
    id: 'project-mobile-carousel',
    chapter: 'projects',
    trigger: 'coarse pointer or narrow project-media viewport',
    fallback: 'vertical document-flow media list',
    reducedMotion: 'static',
    contextCost: 0,
    license: 'MIT',
    sourceUrl: 'https://github.com/davidjerleke/embla-carousel',
    packageName: 'embla-carousel-react',
  },
] as const satisfies readonly VisualEffectDefinition[]

export function getVisualEffectDefinition(id: string): VisualEffectDefinition | undefined {
  return visualEffectManifest.find((effect) => effect.id === id)
}
